/**
 * scripts/dump-index-schema.ts
 *
 * Emits the live `.codegraph-vba/codegraph.db` schema as a markdown file
 * (`docs/index-schema.md`). This is Deliverable 2 of issue #200.
 *
 * Why this script exists
 * ----------------------
 * External tools that want to read the codegraph index directly (the
 * "Pattern B" described in `docs/external-integration.md`) need a stable
 * contract for which tables and columns exist and what their types are.
 * Hand-maintaining that contract drifts the moment a column is added or
 * renamed; this script makes drift impossible by sourcing both the table
 * inventory and the per-column types directly from `sqlite_master` and
 * `PRAGMA table_info`, with the **stable** tags maintained alongside the
 * script (and reviewed in PRs).
 *
 * The committed `docs/index-schema.md` is the golden that ships with each
 * release. The script regenerates it from the live DB on demand:
 *
 *     npm run schema:dump
 *
 * (or `npx tsx scripts/dump-index-schema.ts --out docs/index-schema.md`)
 *
 * The first time a release adds this script, the golden is committed by
 * hand; subsequent regenerations are committed as `chore(schema):` bumps.
 *
 * Stability tagging
 * -----------------
 * The script knows which columns are part of the public stable contract —
 * see `STABLE_COLUMNS` below. Every other column is labeled "implementation
 * detail" in the doc and may change without notice. Adding a column to
 * `STABLE_COLUMNS` is a deliberate, reviewable decision; consumers that
 * built against a stable column are guaranteed it will not be removed.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { execFileSync } from 'node:child_process';

interface ColumnInfo {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: unknown;
  pk: number;
}

interface IndexInfo {
  name: string;
  unique: boolean;
  origin: string; // 'c' (CREATE INDEX), 'u' (UNIQUE), 'pk'
  partial: boolean;
}

/**
 * The canonical "stable" tables — the ones external SQL consumers can rely
 * on. Mirrors the issue's explicit list. The test suite pins this set;
 * adding or removing a name here is a breaking change.
 */
const CANONICAL_TABLES = new Set<string>(['nodes', 'edges', 'unresolved_refs']);

/**
 * The canonical "stable" columns per table. The contract guarantee: any
 * column listed here will not be removed or have its type changed within
 * the v1.x line. Adding new stable columns is allowed (additive change).
 *
 * Every other column is "implementation detail" and may evolve between
 * minor releases — its tag in the emitted doc reflects that.
 */
const STABLE_COLUMNS: Record<string, ReadonlySet<string>> = {
  nodes: new Set([
    'id',
    'kind',
    'name',
    'qualified_name',
    'file_path',
    'language',
    'start_line',
    'end_line',
    'metadata',
  ]),
  edges: new Set(['id', 'source', 'target', 'kind', 'metadata', 'provenance']),
  unresolved_refs: new Set([
    'id',
    'from_node_id',
    'reference_name',
    'reference_kind',
    'line',
    'col',
    'status',
    'metadata',
  ]),
};

/**
 * Tables that are pure infrastructure (auto-populated by the indexer or by
 * SQLite itself) and never part of any consumer contract. We document them
 * for completeness but tag every column as implementation detail, so the
 * output makes their status unambiguous.
 */
const INFRASTRUCTURE_TABLES = new Set<string>([
  'schema_versions',
  'project_metadata',
  'name_segment_vocab',
]);

/**
 * FTS5 virtual tables are auto-generated by SQLite when an FTS5 module is
 * created — the user-facing search goes through the source table
 * (`nodes_fts` is a search index for `nodes`), so we mention them in a
 * single shared section rather than enumerating their shadow columns.
 */
const FTS_SHADOW_PREFIX = 'nodes_fts';

/**
 * Open a fresh temp `node:sqlite` database, apply the canonical schema, and
 * return the live table/column/index metadata. Hermetic — never reads or
 * mutates the user's real `.codegraph-vba/codegraph.db`.
 */
function readLiveSchema(): {
  tables: Map<string, ColumnInfo[]>;
  indexes: Map<string, IndexInfo[]>;
  order: string[];
} {
  const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'codegraph-dump-'));
  const dbPath = path.join(tempDir, 'live.db');
  const db = new DatabaseSync(dbPath);
  const schemaSql = fs.readFileSync(
    path.resolve(__dirname, '..', 'src', 'db', 'schema.sql'),
    'utf-8',
  );
  db.exec(schemaSql);

  const tableRows = db
    .prepare(
      `SELECT name FROM sqlite_master
       WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
       ORDER BY name`,
    )
    .all() as Array<{ name: string }>;
  const tables = new Map<string, ColumnInfo[]>();
  const indexes = new Map<string, IndexInfo[]>();
  const order: string[] = [];
  for (const { name } of tableRows) {
    const cols = db.prepare(`PRAGMA table_info(${name})`).all() as ColumnInfo[];
    tables.set(name, cols);
    const idxRows = db
      .prepare(`PRAGMA index_list(${name})`)
      .all() as Array<{
      name: string;
      unique: number;
      origin: string;
      partial: number;
    }>;
    indexes.set(
      name,
      idxRows.map((r) => ({
        name: r.name,
        unique: r.unique === 1,
        origin: r.origin,
        partial: r.partial === 1,
      })),
    );
    order.push(name);
  }
  db.close();
  fs.rmSync(tempDir, { recursive: true, force: true });
  return { tables, indexes, order };
}

function escapeMarkdown(s: string): string {
  // Pipe characters break pipe-delimited tables; backticks would render as
  // code. Both are exceedingly rare in column / table names, but a
  // defensive escape keeps the doc readable if they ever appear.
  return s.replace(/\|/g, '\\|').replace(/`/g, '\\`');
}

function renderColumnType(col: ColumnInfo): string {
  const nullable = col.notnull === 0 ? 'NULL' : 'NOT NULL';
  const defaultClause =
    col.dflt_value !== null && col.dflt_value !== undefined
      ? ` DEFAULT ${JSON.stringify(col.dflt_value)}`
      : '';
  const pk = col.pk > 0 ? ` PRIMARY KEY (part ${col.pk})` : '';
  return `${col.type || 'ANY'} ${nullable}${defaultClause}${pk}`.trim();
}

function stabilityTagFor(table: string, column: string): 'stable' | 'implementation detail' {
  const stableCols = STABLE_COLUMNS[table];
  if (stableCols && stableCols.has(column)) return 'stable';
  return 'implementation detail';
}

/**
 * Group FTS5 shadow tables (`nodes_fts`, `nodes_fts_config`, etc.) into a
 * single "FTS5 internal tables" section. They are auto-managed by SQLite
 * and never queried directly by consumers.
 */
function partitionTables(order: string[]): {
  canonical: string[];
  infrastructure: string[];
  fts: string[];
  other: string[];
} {
  const canonical: string[] = [];
  const infrastructure: string[] = [];
  const fts: string[] = [];
  const other: string[] = [];
  for (const name of order) {
    if (CANONICAL_TABLES.has(name)) canonical.push(name);
    else if (INFRASTRUCTURE_TABLES.has(name)) infrastructure.push(name);
    else if (name.startsWith(FTS_SHADOW_PREFIX)) fts.push(name);
    else other.push(name);
  }
  return { canonical, infrastructure, fts, other };
}

function renderTable(
  table: string,
  columns: ColumnInfo[],
  indexes: IndexInfo[],
  isStable: boolean,
): string {
  const lines: string[] = [];
  lines.push(`## ${table}`);
  lines.push('');
  lines.push(
    isStable
      ? '**Stability: stable.** Part of the public contract — columns and types here are pinned across the v1.x line. Adding columns is allowed; removing or retyping is a breaking change.'
      : '**Stability: implementation detail.** Internal to the indexer; may change between minor releases without notice.',
  );
  lines.push('');
  lines.push('| Column | Type | Stability |');
  lines.push('|---|---|---|');
  for (const col of columns) {
    lines.push(
      `| \`${escapeMarkdown(col.name)}\` | ${escapeMarkdown(renderColumnType(col))} | ${stabilityTagFor(table, col.name)} |`,
    );
  }
  lines.push('');
  if (indexes.length > 0) {
    lines.push('### Indexes');
    lines.push('');
    lines.push('| Name | Unique | Origin | Partial |');
    lines.push('|---|---|---|---|');
    for (const idx of indexes) {
      lines.push(
        `| \`${escapeMarkdown(idx.name)}\` | ${idx.unique ? 'yes' : 'no'} | ${idx.origin} | ${idx.partial ? 'yes' : 'no'} |`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

function renderFtsSection(tables: string[], tableMap: Map<string, ColumnInfo[]>): string {
  if (tables.length === 0) return '';
  const lines: string[] = [];
  // The FTS5 shadow tables are auto-generated by SQLite when the
  // `nodes_fts` virtual table is created. Each is its own `## table`
  // heading (rather than a single shared `### table` subsection) so the
  // drift-detection test can verify each one is documented. They are
  // tagged "implementation detail" — external tools should not query
  // them directly.
  for (const name of tables) {
    const cols = tableMap.get(name) ?? [];
    lines.push(`## ${name}`);
    lines.push('');
    lines.push(
      '**Stability: implementation detail.** Auto-generated by SQLite for the `nodes_fts` virtual table. External tools MUST NOT query this table directly.',
    );
    lines.push('');
    lines.push('| Column | Type |');
    lines.push('|---|---|');
    for (const col of cols) {
      lines.push(`| \`${escapeMarkdown(col.name)}\` | ${escapeMarkdown(col.type || 'ANY')} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function buildDoc(tables: Map<string, ColumnInfo[]>, indexes: Map<string, IndexInfo[]>, order: string[]): string {
  const { canonical, infrastructure, fts, other } = partitionTables(order);
  const parts: string[] = [];
  parts.push('# codegraph-vba index — SQL schema reference');
  parts.push('');
  parts.push(
    `This document is the published SQL contract for the \`.codegraph-vba/codegraph.db\` index. It is **auto-generated** by \`scripts/dump-index-schema.ts\` from the canonical schema in \`src/db/schema.sql\` (issue #200, Deliverable 2).`,
  );
  parts.push('');
  parts.push('Regenerate with `npm run schema:dump` after any schema change.');
  parts.push('');
  parts.push('## How to read this doc');
  parts.push('');
  parts.push(
    'Each table is tagged with a **Stability** line in its header. Per-column stability is in the third column of every table.',
  );
  parts.push('');
  parts.push('- **`stable`** — part of the public contract. External tools may rely on these column names and types within the v1.x line. Removing or retyping is a breaking change and requires a major version bump.');
  parts.push('- **`implementation detail`** — internal to the indexer. May be added, removed, or retyped between minor releases. External tools MUST NOT depend on these.');
  parts.push('');
  parts.push('## Canonical (public) tables');
  parts.push('');
  parts.push(
    'The three tables below are the contract surface for external SQL consumers (see `docs/external-integration.md` §3 for the pattern, and [Dysflow#1015](https://github.com/DysTelefonica/dysflow/issues/1015) for the cross-tool motivation). The column list mirrors the row keys `CodeGraph.searchNodes`, `getCallers`, `getCallees`, and `getImpactRadius` expose on the JSON surface.',
  );
  parts.push('');
  for (const t of canonical) {
    parts.push(renderTable(t, tables.get(t) ?? [], indexes.get(t) ?? [], true));
  }
  parts.push('## Infrastructure tables');
  parts.push('');
  parts.push(
    'Internal bookkeeping for the indexer — versions, project metadata, the prompt-hook segment vocabulary. Documented here for completeness; no external tool should query them.',
  );
  parts.push('');
  for (const t of infrastructure) {
    parts.push(renderTable(t, tables.get(t) ?? [], indexes.get(t) ?? [], false));
  }
  if (other.length > 0) {
    parts.push('## Other tables');
    parts.push('');
    for (const t of other) {
      parts.push(renderTable(t, tables.get(t) ?? [], indexes.get(t) ?? [], false));
    }
  }
  parts.push(renderFtsSection(fts, tables));
  parts.push('## Notes for consumers');
  parts.push('');
  parts.push(
    '- **`metadata` columns are JSON.** `nodes.metadata`, `edges.metadata`, `unresolved_refs.metadata`, and `unresolved_refs.candidates` carry a JSON string. Use SQLite\'s `json_extract()` to read individual keys; the keys inside the JSON object are NOT covered by the stable contract — see the per-feature doc (e.g. `docs/vba-stub-repoint-decision.md` for `edges.metadata.repointDecision`).',
  );
  parts.push(
    '- **`status` on `unresolved_refs`** is the lifecycle field (`pending` → resolved-and-deleted, or `failed` / `declined-runtime` / `declined-ambiguous` / `declined-not-found`). See `docs/vba-stub-repoint-decision.md` for the resolution taxonomy and `docs/vba-reference-kinds.md` for the `reference_kind` taxonomy.',
  );
  parts.push(
    '- **FTS5 queries** go through the `nodes_fts` virtual table; the shadow tables (`nodes_fts_config`, `nodes_fts_data`, `nodes_fts_docsize`, `nodes_fts_idx`) are managed by SQLite. External tools should treat the `nodes_fts_*` shadow tables as off-limits.',
  );
  parts.push(
    "- **`provenance`** on `edges` is `'static'` (default, null in old rows) or `'heuristic'` for synthesized edges. Stable: the column is part of the contract, but the value space may grow with new synthesizer types — see `docs/design/callback-edge-synthesis.md`.",
  );
  parts.push('');
  parts.push('## Cross-references');
  parts.push('');
  parts.push('- [`docs/external-integration.md`](external-integration.md) — Pattern A (subprocess spawn) and the JSON contracts.');
  parts.push('- [`docs/vba-stub-repoint-decision.md`](vba-stub-repoint-decision.md) — `repointDecision` taxonomy for `edges.metadata`.');
  parts.push('- [`docs/vba-reference-kinds.md`](vba-reference-kinds.md) — `reference_kind` taxonomy for `unresolved_refs`.');
  parts.push('- Sister issue [Dysflow#1015](https://github.com/DysTelefonica/dysflow/issues/1015) — this doc unblocks its Path 1 fix.');
  parts.push('- Issue #200 — this issue.');
  parts.push('');
  return parts.join('\n');
}

function parseArgs(argv: string[]): { out: string; dryRun: boolean } {
  let out = path.resolve(__dirname, '..', 'docs', 'index-schema.md');
  let dryRun = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') {
      const next = argv[i + 1];
      if (!next) throw new Error('--out requires a path argument');
      out = path.resolve(next);
      i++;
    } else if (a === '--dry-run') {
      dryRun = true;
    }
  }
  return { out, dryRun };
}

function main(): number {
  const args = parseArgs(process.argv.slice(2));
  const { tables, indexes, order } = readLiveSchema();
  const markdown = buildDoc(tables, indexes, order);

  if (args.dryRun) {
    process.stdout.write(markdown);
    return 0;
  }

  fs.mkdirSync(path.dirname(args.out), { recursive: true });
  fs.writeFileSync(args.out, markdown, 'utf-8');
  process.stdout.write(`Wrote ${args.out} (${markdown.length} chars, ${order.length} tables).\n`);
  return 0;
}

main();